if(NOT DEFINED MAHLER OR NOT DEFINED TEST_OUTPUT)
    message(FATAL_ERROR "MAHLER and TEST_OUTPUT are required")
endif()
file(MAKE_DIRECTORY "${TEST_OUTPUT}")

function(run expected_exit)
    execute_process(COMMAND "${MAHLER}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT "${status}" STREQUAL "${expected_exit}")
        message(FATAL_ERROR "${ARGN}: exit ${status}, expected ${expected_exit}: ${error}")
    endif()
    if(expected_exit EQUAL 0 AND NOT error STREQUAL "")
        message(FATAL_ERROR "${ARGN}: unexpected stderr ${error}")
    endif()
    if(NOT expected_exit EQUAL 0 AND NOT error MATCHES "^error: ")
        message(FATAL_ERROR "${ARGN}: error message missing")
    endif()
endfunction()

set(first "${TEST_OUTPUT}/first.csv")
set(second "${TEST_OUTPUT}/second.csv")
set(occurrences "${TEST_OUTPUT}/occurrences.csv")
set(json_file "${TEST_OUTPUT}/summary.json")
run(0 scan --max 9910 --output "${first}" --occurrences "${occurrences}")
run(0 scan --max 9910 --output "${second}")
file(SHA256 "${first}" first_hash)
file(SHA256 "${second}" second_hash)
if(NOT first_hash STREQUAL second_hash)
    message(FATAL_ERROR "repeated CSV summaries differ")
endif()
file(STRINGS "${first}" lines)
list(LENGTH lines line_count)
if(NOT line_count EQUAL 9911)
    message(FATAL_ERROR "CSV should contain header plus 9910 targets")
endif()
list(GET lines 9910 last_row)
if(NOT last_row STREQUAL "9910,4,38530,188,true,4,38342")
    message(FATAL_ERROR "incorrect last CSV row: ${last_row}")
endif()
file(STRINGS "${occurrences}" occurrence_rows REGEX "^9910,")
list(LENGTH occurrence_rows occurrence_count)
if(NOT occurrence_count EQUAL 4)
    message(FATAL_ERROR "9910 should have four early occurrence records")
endif()
file(READ "${first}.manifest.json" manifest)
string(JSON manifest_max GET "${manifest}" maximum)
string(JSON manifest_count GET "${manifest}" target_records)
string(JSON manifest_occurrences GET "${manifest}" occurrences records)
if(NOT manifest_max STREQUAL "9910" OR NOT manifest_count EQUAL 9910 OR manifest_occurrences LESS 4)
    message(FATAL_ERROR "manifest range or occurrence count is incorrect")
endif()
run(0 scan --max 100 --format json --output "${json_file}")
file(READ "${json_file}" dataset)
string(JSON schema GET "${dataset}" schema_version)
string(JSON record_count LENGTH "${dataset}" records)
string(JSON twelfth_first GET "${dataset}" records 11 first_position)
if(NOT schema EQUAL 1 OR NOT record_count EQUAL 100 OR NOT twelfth_first STREQUAL "1")
    message(FATAL_ERROR "JSON summary schema or content is incorrect")
endif()
run(2 scan --max 0 --output "${first}")
run(2 scan --max 1000001 --output "${first}")
run(2 scan --max 10 --output "${first}" --manifest "${first}")
run(2 scan --max 10 --output "${first}" --occurrences "${first}")
run(2 scan --max 10 --output "${first}" --format xml)
run(2 scan --max 10 --output "${first}" --max 11)
run(2 benchmark --max 10 --repeat 0)
run(2 benchmark --max 10 --engine unknown)
run(3 scan --max 18446744073709551616 --output "${first}")

execute_process(COMMAND "${MAHLER}" benchmark --max 100 --engine window --repeat 2
    RESULT_VARIABLE window_status OUTPUT_VARIABLE window_benchmark ERROR_VARIABLE window_error)
execute_process(COMMAND "${MAHLER}" benchmark --max 100 --engine reconstruct --repeat 2
    RESULT_VARIABLE reconstruct_status OUTPUT_VARIABLE reconstruct_benchmark ERROR_VARIABLE reconstruct_error)
if(NOT window_status EQUAL 0 OR NOT reconstruct_status EQUAL 0 OR
   NOT window_error STREQUAL "" OR NOT reconstruct_error STREQUAL "")
    message(FATAL_ERROR "benchmark commands failed")
endif()
string(JSON window_hash GET "${window_benchmark}" result_fnv1a64)
string(JSON reconstruct_hash GET "${reconstruct_benchmark}" result_fnv1a64)
if(NOT window_hash STREQUAL reconstruct_hash)
    message(FATAL_ERROR "benchmark engines produced different summaries")
endif()
