file(MAKE_DIRECTORY "${TEST_OUTPUT}")
function(run expected)
    execute_process(COMMAND "${MAHLER}" ${ARGN} RESULT_VARIABLE status ERROR_VARIABLE error)
    if(NOT "${status}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: ${status}, expected ${expected}: ${error}")
    endif()
endfunction()
run(0 ulam --max 9 --layer combined --output "${TEST_OUTPUT}/nine.svg")
file(READ "${TEST_OUTPUT}/nine.svg" svg)
if(NOT svg MATCHES "x=\"1\" y=\"1\"[^\n]*<title>1</title>" OR
   NOT svg MATCHES "x=\"2\" y=\"0\"[^\n]*<title>3</title>" OR
   NOT svg MATCHES "x=\"2\" y=\"2\"[^\n]*<title>9</title>")
    message(FATAL_ERROR "SVG coordinates/orientation incorrect")
endif()
run(0 plot-data --max 100 --output-dir "${TEST_OUTPUT}/data")
file(READ "${TEST_OUTPUT}/data/manifest.json" manifest)
string(JSON early GET "${manifest}" early_targets)
string(JSON occurrences GET "${manifest}" early_occurrences)
if(NOT early EQUAL 45 OR NOT occurrences EQUAL 45)
    message(FATAL_ERROR "plot data totals incorrect")
endif()
file(STRINGS "${TEST_OUTPUT}/data/groups.csv" group REGEX "^2,")
if(NOT group STREQUAL "2,90,45,45,0.5,21,12,0.571428571429,69,33,0.478260869565,1")
    message(FATAL_ERROR "plot denominators incorrect: ${group}")
endif()
run(2 ulam --max 10001 --layer early --output "${TEST_OUTPUT}/large.svg")
run(2 ulam --max 100 --layer unknown --output "${TEST_OUTPUT}/bad.svg")
run(2 ulam --max 100 --layer early --output "${TEST_OUTPUT}/bad.svg" --cell-size 17)
run(2 plot-data --max 1000001 --output-dir "${TEST_OUTPUT}/bad")
if(HAVE_PNG)
    run(0 ulam --max 100 --layer combined --output "${TEST_OUTPUT}/hundred.png")
    file(READ "${TEST_OUTPUT}/hundred.png" signature LIMIT 8 HEX)
    if(NOT signature STREQUAL "89504e470d0a1a0a")
        message(FATAL_ERROR "PNG signature missing")
    endif()
    execute_process(COMMAND "${PNG_CHECKER}" "${TEST_OUTPUT}/hundred.png" RESULT_VARIABLE pixel_status)
    if(NOT pixel_status EQUAL 0)
        message(FATAL_ERROR "decoded PNG pixels incorrect")
    endif()
else()
    run(2 ulam --max 100 --layer early --output "${TEST_OUTPUT}/hundred.png")
endif()
